CREATE TABLE DMKHOA (
    MAKHOA CHAR(2) PRIMARY KEY,
    TENKHOA NVARCHAR2(30)
);

CREATE TABLE DMMH (
    MAMH CHAR(2) PRIMARY KEY,
    TENMH NVARCHAR2(35),
    SOTIET NUMBER(3)
);

CREATE TABLE DMSV (
    MASV CHAR(3) PRIMARY KEY,
    HOSV NVARCHAR2(30),
    TENSV NVARCHAR2(10),
    PHAI NVARCHAR2(3),
    NGAYSINH DATE,
    NOISINH NVARCHAR2(25),
    MAKH CHAR(2),
    HOCBONG NUMBER(10,0),
    CONSTRAINT FK_DMSV_DMKHOA FOREIGN KEY (MAKH) REFERENCES DMKHOA(MAKHOA)
);

CREATE TABLE KETQUA (
    MASV CHAR(3),
    MAMH CHAR(2),
    PRIMARY KEY (MASV, MAMH),
    CONSTRAINT FK_KQ_DMSV FOREIGN KEY (MASV) REFERENCES DMSV(MASV),
    CONSTRAINT FK_KQ_DMMH FOREIGN KEY (MAMH) REFERENCES DMMH(MAMH)
);

INSERT ALL 
    INTO DMKHOA (MAKHOA, TENKHOA) VALUES ('AV', N'Anh Văn')
    INTO DMKHOA (MAKHOA, TENKHOA) VALUES ('TH', N'Công Nghệ Thông Tin')
    INTO DMKHOA (MAKHOA, TENKHOA) VALUES ('TR', N'Triết Học')
    INTO DMKHOA (MAKHOA, TENKHOA) VALUES ('VL', N'Vật Lý')
    INTO DMKHOA (MAKHOA, TENKHOA) VALUES ('KT', N'Kinh Tế')
SELECT * FROM dual;

INSERT ALL
    INTO DMMH (MAMH, TENMH, SOTIET) VALUES ('01', N'Cơ Sở Dữ Liệu', 45)
    INTO DMMH (MAMH, TENMH, SOTIET) VALUES ('02', N'Trí Tuệ Nhân Tạo', 45)
    INTO DMMH (MAMH, TENMH, SOTIET) VALUES ('03', N'Truyền Tin', 30)
    INTO DMMH (MAMH, TENMH, SOTIET) VALUES ('04', N'Đồ Họa', 60)
    INTO DMMH (MAMH, TENMH, SOTIET) VALUES ('05', N'Văn Phạm Anh Văn', 45)
    INTO DMMH (MAMH, TENMH, SOTIET) VALUES ('06', N'Kỹ Thuật Lập Trình', 60)
SELECT * FROM dual;

INSERT ALL
    INTO DMSV (MASV, HOSV, TENSV, PHAI, NGAYSINH, NOISINH, MAKH, HOCBONG) 
    VALUES ('A01', N'Nguyễn Thị', N'Hải', N'Nữ', TO_DATE('2005-02-23', 'YYYY-MM-DD'), N'Hà Nội', 'TH', 130000)
    INTO DMSV (MASV, HOSV, TENSV, PHAI, NGAYSINH, NOISINH, MAKH, HOCBONG) 
    VALUES ('A02', N'Trần Văn', N'Chính', N'Nam', TO_DATE('2005-12-24', 'YYYY-MM-DD'), N'Bình Định', 'VL', 150000)
    INTO DMSV (MASV, HOSV, TENSV, PHAI, NGAYSINH, NOISINH, MAKH, HOCBONG) 
    VALUES ('A03', N'Lê Thu Bạch', N'Yến', N'Nữ', TO_DATE('2005-02-21', 'YYYY-MM-DD'), N'TP HCM', 'TH', 170000)
    INTO DMSV (MASV, HOSV, TENSV, PHAI, NGAYSINH, NOISINH, MAKH, HOCBONG) 
    VALUES ('A04', N'Trần Anh', N'Tuấn', N'Nam', TO_DATE('2005-12-20', 'YYYY-MM-DD'), N'Hà Nội', 'AV', 80000)
    INTO DMSV (MASV, HOSV, TENSV, PHAI, NGAYSINH, NOISINH, MAKH, HOCBONG) 
    VALUES ('B01', N'Trần Thanh', N'Mai', N'Nữ', TO_DATE('2005-08-12', 'YYYY-MM-DD'), N'Hải Phòng', 'TR', 0)
    INTO DMSV (MASV, HOSV, TENSV, PHAI, NGAYSINH, NOISINH, MAKH, HOCBONG) 
    VALUES ('B02', N'Trần Thị Thu', N'Thủy', N'Nữ', TO_DATE('2005-01-02', 'YYYY-MM-DD'), N'TP HCM', 'AV', 0)
    INTO DMSV (MASV, HOSV, TENSV, PHAI, NGAYSINH, NOISINH, MAKH, HOCBONG) 
    VALUES ('B03', N'Lê Ngọc', N'Thuận', N'Nam', TO_DATE('2005-10-15', 'YYYY-MM-DD'), N'Phú Yên', 'TH', 200000)
SELECT * FROM dual;

INSERT ALL
    INTO KETQUA (MASV, MAMH) VALUES ('A01', '01')
    INTO KETQUA (MASV, MAMH) VALUES ('A01', '02')
    INTO KETQUA (MASV, MAMH) VALUES ('A01', '03')
    INTO KETQUA (MASV, MAMH) VALUES ('A02', '01')
    INTO KETQUA (MASV, MAMH) VALUES ('A02', '03')
    INTO KETQUA (MASV, MAMH) VALUES ('A02', '05')
    INTO KETQUA (MASV, MAMH) VALUES ('A03', '01')
    INTO KETQUA (MASV, MAMH) VALUES ('A03', '03')
    INTO KETQUA (MASV, MAMH) VALUES ('A04', '05')
    INTO KETQUA (MASV, MAMH) VALUES ('A04', '06')
    INTO KETQUA (MASV, MAMH) VALUES ('B01', '01')
    INTO KETQUA (MASV, MAMH) VALUES ('B02', '02')
    INTO KETQUA (MASV, MAMH) VALUES ('B03', '01')
    INTO KETQUA (MASV, MAMH) VALUES ('B03', '04')
SELECT * FROM dual;