CREATE TABLE PHONGBAN (
    MAPHONG INT PRIMARY KEY,
    TENPHONG NVARCHAR2(50),
    TRPHONG CHAR(9),
    NG_NHANCHUC DATE
);

CREATE TABLE NHANVIEN (
    HONV NVARCHAR2(15),
    TENLOT NVARCHAR2(15),
    TENNV NVARCHAR2(15),
    MANV CHAR(9) PRIMARY KEY,
    NGAYSINH DATE,
    DIACHI NVARCHAR2(50),
    PHAI NVARCHAR2(3),
    LUONG NUMBER(10, 2),
    MA_NQL CHAR(9) CONSTRAINT FK_NV_NQL REFERENCES NHANVIEN(MANV),
    PHONG INT CONSTRAINT FK_NV_PB REFERENCES PHONGBAN(MAPHONG)
);


ALTER TABLE PHONGBAN ADD CONSTRAINT FK_PB_NV FOREIGN KEY (TRPHONG) REFERENCES NHANVIEN(MANV);

CREATE TABLE DIADIEM_PHG (
    MAPHONG INT CONSTRAINT FK_DD_PB REFERENCES PHONGBAN(MAPHONG),
    DIADIEM NVARCHAR2(30),
    PRIMARY KEY (MAPHONG, DIADIEM)
);


CREATE TABLE DEAN (
    TENDA NVARCHAR2(50),
    MADA INT PRIMARY KEY,
    DDIEM_DA NVARCHAR2(30),
    PHONG INT CONSTRAINT FK_DA_PB REFERENCES PHONGBAN(MAPHONG)
);

CREATE TABLE PHANCONG (
    MA_NVIEN CHAR(9) CONSTRAINT FK_PC_NV REFERENCES NHANVIEN(MANV),
    MADA INT CONSTRAINT FK_PC_DA REFERENCES DEAN(MADA),
    THOIGIAN NUMBER(5, 2),
    PRIMARY KEY (MA_NVIEN, MADA)
);

CREATE TABLE THANNHAN (
    MA_NVIEN CHAR(9) CONSTRAINT FK_TN_NV REFERENCES NHANVIEN(MANV),
    TENTN NVARCHAR2(30),
    PHAI NVARCHAR2(3),
    NGAYSINH DATE,
    QUANHE NVARCHAR2(15),
    PRIMARY KEY (MA_NVIEN, TENTN)
);

INSERT INTO PHONGBAN VALUES (1, N'Quản lý', NULL, DATE '2019-06-19');
INSERT INTO PHONGBAN VALUES (2, N'Kế toán', NULL, DATE '2022-03-10');
INSERT INTO PHONGBAN VALUES (3, N'Nhân sự', NULL, DATE '2023-08-15');
INSERT INTO PHONGBAN VALUES (4, N'Điều hành', NULL, DATE '2021-01-01');
INSERT INTO PHONGBAN VALUES (5, N'Nghiên cứu', NULL, DATE '2020-05-22');
INSERT INTO PHONGBAN VALUES (6, N'IT', NULL, DATE '2021-12-01');
INSERT INTO PHONGBAN VALUES (7, N'Marketing', NULL, DATE '2022-05-20');
INSERT INTO PHONGBAN VALUES (8, N'Kỹ thuật', NULL, DATE '2020-10-10');
INSERT INTO PHONGBAN VALUES (9, N'Pháp chế', NULL, DATE '2024-01-05');
INSERT INTO PHONGBAN VALUES (10, N'Hậu cần', NULL, DATE '2023-02-14');

INSERT INTO NHANVIEN VALUES (N'Đinh', N'Bá', N'Tiên', '001', DATE '1985-01-01', N'TP HCM', N'Nam', 30000, NULL, 5);
INSERT INTO NHANVIEN VALUES (N'Nguyễn', N'Thanh', N'Tùng', '002', DATE '1975-05-12', N'Đà Nẵng', N'Nam', 40000, '001', 5);
INSERT INTO NHANVIEN VALUES (N'Bùi', N'Thị', N'Cúc', '003', DATE '1990-10-20', N'Hà Nội', N'Nữ', 25000, '001', 4);
INSERT INTO NHANVIEN VALUES (N'Lê', N'Văn', N'An', '004', DATE '1988-07-07', N'Cần Thơ', N'Nam', 35000, '002', 1);
INSERT INTO NHANVIEN VALUES (N'Trần', N'Hồng', N'Quang', '005', DATE '1995-12-12', N'Vũng Tàu', N'Nam', 28000, '003', 5);
INSERT INTO NHANVIEN VALUES (N'Phạm', N'Thị', N'Hoa', '006', DATE '1992-03-15', N'Đồng Nai', N'Nữ', 32000, '002', 6);
INSERT INTO NHANVIEN VALUES (N'Vũ', N'Hoàng', n'Long', '007', DATE '1989-11-25', N'TP HCM', N'Nam', 37000, '004', 7);
INSERT INTO NHANVIEN VALUES (N'Đỗ', N'Quốc', N'Bảo', '008', DATE '1994-06-30', N'Hà Nội', N'Nam', 31000, '003', 8);
INSERT INTO NHANVIEN VALUES (N'Hồ', N'Thanh', N'Thảo', '009', DATE '1997-09-09', N'Huế', N'Nữ', 29000, '001', 5);
INSERT INTO NHANVIEN VALUES (N'Lý', N'Minh', N'Anh', '010', DATE '1991-04-18', N'Bình Dương', N'Nữ', 33000, '004', 1);

UPDATE PHONGBAN SET TRPHONG = '004' WHERE MAPHONG = 1;
UPDATE PHONGBAN SET TRPHONG = '002' WHERE MAPHONG = 2;
UPDATE PHONGBAN SET TRPHONG = '010' WHERE MAPHONG = 3;
UPDATE PHONGBAN SET TRPHONG = '003' WHERE MAPHONG = 4;
UPDATE PHONGBAN SET TRPHONG = '001' WHERE MAPHONG = 5;
UPDATE PHONGBAN SET TRPHONG = '006' WHERE MAPHONG = 6;
UPDATE PHONGBAN SET TRPHONG = '007' WHERE MAPHONG = 7;
UPDATE PHONGBAN SET TRPHONG = '008' WHERE MAPHONG = 8;
UPDATE PHONGBAN SET TRPHONG = '005' WHERE MAPHONG = 9;
UPDATE PHONGBAN SET TRPHONG = '009' WHERE MAPHONG = 10;

INSERT INTO DIADIEM_PHG VALUES (1, N'TP HCM');
INSERT INTO DIADIEM_PHG VALUES (2, N'TP HCM');
INSERT INTO DIADIEM_PHG VALUES (3, N'Hà Nội');
INSERT INTO DIADIEM_PHG VALUES (4, N'Hà Nội');
INSERT INTO DIADIEM_PHG VALUES (5, N'Vũng Tàu');
INSERT INTO DIADIEM_PHG VALUES (5, N'Nha Trang');
INSERT INTO DIADIEM_PHG VALUES (6, N'TP HCM');
INSERT INTO DIADIEM_PHG VALUES (7, N'Đà Nẵng');
INSERT INTO DIADIEM_PHG VALUES (8, N'Bình Dương');
INSERT INTO DIADIEM_PHG VALUES (9, N'TP HCM');

INSERT INTO DEAN VALUES (N'Sản phẩm X', 1, N'Vũng Tàu', 5);
INSERT INTO DEAN VALUES (N'Sản phẩm Y', 2, N'Nha Trang', 5);
INSERT INTO DEAN VALUES (N'Sản phẩm Z', 3, N'TP HCM', 5);
INSERT INTO DEAN VALUES (N'Tin học hóa', 10, N'Hà Nội', 4);
INSERT INTO DEAN VALUES (N'Đào tạo', 20, N'TP HCM', 1);
INSERT INTO DEAN VALUES (N'Phát triển Web', 40, N'TP HCM', 6);
INSERT INTO DEAN VALUES (N'Chiến dịch Mùa hè', 50, N'Đà Nẵng', 7);
INSERT INTO DEAN VALUES (N'Nâng cấp xưởng', 60, N'Bình Dương', 8);
INSERT INTO DEAN VALUES (N'Tuyển dụng K5', 70, N'TP HCM', 3);
INSERT INTO DEAN VALUES (N'Hợp đồng quốc tế', 80, N'TP HCM', 9);

INSERT INTO PHANCONG VALUES ('001', 1, 32.5);
INSERT INTO PHANCONG VALUES ('001', 2, 8.0);
INSERT INTO PHANCONG VALUES ('002', 3, 10.0);
INSERT INTO PHANCONG VALUES ('003', 10, 20.0);
INSERT INTO PHANCONG VALUES ('004', 20, 15.0);
INSERT INTO PHANCONG VALUES ('006', 40, 40.0);
INSERT INTO PHANCONG VALUES ('007', 50, 25.0);
INSERT INTO PHANCONG VALUES ('008', 60, 30.0);
INSERT INTO PHANCONG VALUES ('010', 20, 10.0);
INSERT INTO PHANCONG VALUES ('005', 80, 22.0);

INSERT INTO THANNHAN VALUES ('001', N'Tiên', N'Nữ', DATE '2010-05-05', N'Con gái');
INSERT INTO THANNHAN VALUES ('001', N'Mạnh', N'Nam', DATE '2012-07-07', N'Con trai');
INSERT INTO THANNHAN VALUES ('002', N'Lan', N'Nữ', DATE '1980-03-03', N'Vợ');
INSERT INTO THANNHAN VALUES ('003', N'Hùng', N'Nam', DATE '1992-01-01', N'Chồng');
INSERT INTO THANNHAN VALUES ('004', N'Dũng', N'Nam', DATE '2015-10-10', N'Con trai');
INSERT INTO THANNHAN VALUES ('006', N'Ngọc', N'Nữ', DATE '2018-12-20', N'Con gái');
INSERT INTO THANNHAN VALUES ('007', N'Hạnh', N'Nữ', DATE '1990-05-05', N'Vợ');
INSERT INTO THANNHAN VALUES ('008', N'Sơn', N'Nam', DATE '1970-01-01', N'Bố');
INSERT INTO THANNHAN VALUES ('009', N'Hải', N'Nam', DATE '2020-02-02', N'Con trai');
INSERT INTO THANNHAN VALUES ('010', N'Hương', N'Nữ', DATE '1995-03-03', N'Em gái');

COMMIT;